/**
 * Advance widths for the six PDF base-14 faces the exporter uses, in 1/1000 em.
 *
 * Base-14 fonts are the ones every PDF reader already has, so nothing has to be
 * embedded and the files stay a few kB. The trade is that the exporter has to
 * know their metrics to wrap a line, and it has to know them the same way on
 * every machine — measuring the reader's own fonts at download time would let
 * the same record paginate differently depending on who exported it.
 *
 * Generated by measuring the genuine Adobe faces, then checked against the
 * published AFM values (see tests). Do not hand-edit: each entry is a palette of
 * the distinct widths in the face plus one index character per code point from
 * 32 to 255, which is what keeps the whole table under 2 kB.
 */
export interface FontWidths {
  palette: number[];
  indices: string;
}

export const FIRST_CODE = 32;
export const LAST_CODE = 255;
/** Added to a palette index to keep every character printable and unescaped. */
export const INDEX_OFFSET = 40;

export const FONT_WIDTHS: Record<string, FontWidths> = {
  'Times-Roman': {
    palette: [
      0, 180, 200, 250, 276, 278, 300, 310, 333, 350, 389, 400, 408, 444, 453, 469, 480, 500, 541,
      549, 556, 564, 576, 611, 667, 722, 744, 750, 760, 778, 833, 889, 921, 944, 980, 1000,
    ],
    indices:
      '+0499FE)009=+0+-9999999999--===5HA@@A?<AA02A?GAA<A@<?AAIAA?0-079059595099--9-E999902-99A9958*8:(B(095K990K<0G(?((005519K0J20A(5A+09999*90D,9=(D03;..0>6+0./9CCC5AAAAAAG@????0000AAAAAAA=AAAAAA<9555555@55555----9999999;99999999',
  },
  'Times-Bold': {
    palette: [
      0, 220, 250, 278, 300, 330, 333, 350, 389, 394, 400, 444, 500, 520, 540, 549, 555, 556, 570,
      576, 581, 611, 667, 722, 744, 747, 750, 778, 833, 930, 944, 1000,
    ],
    indices:
      '*.844GD+..4:*.*+4444444444..:::4E?>??>=CC04C>F?C=C?9>??G??>.+.<4.49393.49+.9+D949930.94?4431)15(@(.44G44.G9.G(>((..44/4G.G0.?(3?*.4444)4.A,4:(A.27,,.;6*.,-4BBB4??????G?>>>>0000??CCCCC:C?????=9444444?33333++++4944444749999494',
  },
  'Times-Italic': {
    palette: [
      0, 214, 250, 275, 276, 278, 300, 310, 333, 350, 389, 400, 420, 422, 444, 500, 523, 541, 549,
      556, 576, 611, 667, 675, 722, 744, 750, 760, 778, 833, 889, 920, 944, 980, 1000,
    ],
    indices:
      '*0477ED)007?*0*-777777777700???7G==>@==@@06>;E>@=@=7;@=E=;;2-257077676-77--6-@777722-76>6623+39(A(07;F770J70H(;((00;;17F0I20>(2;*27777+70C,7?(C03:..0<8*0./7BBB7======F>====0000@>@@@@@?@@@@@;=7777777>66666----7777777:77777676',
  },
  Helvetica: {
    palette: [
      0, 191, 222, 260, 278, 333, 334, 350, 355, 365, 370, 389, 400, 469, 500, 537, 549, 556, 576,
      584, 611, 667, 722, 737, 744, 778, 833, 834, 889, 944, 1000, 1015,
    ],
    indices:
      ',,099D=)--3;,-,,9999999999,,;;;9G==>>=<A>,6=9B>A=A>=<>=E==<,,,59-99699,99**6*B9999-6,96>666.+.;(@(*9-F99-F=-F(<((**--/9F-F6-E(6=,-9999+9-?29;(?-48---:7,--19CCC<======F>====,,,,>>AAAAA;A>>>>==<999999D69999,,,,99999998<9999696',
  },
  'Helvetica-Bold': {
    palette: [
      0, 238, 278, 280, 333, 350, 365, 370, 389, 400, 474, 500, 549, 556, 576, 584, 611, 667, 722,
      737, 744, 778, 833, 834, 889, 944, 975, 1000,
    ],
    indices:
      '*,255@:),,07*,**5555555555,,7778B::::98=:*5:8>:=9=:98:9A998,*,75,58585,88**5*@888805,85=5530+07(<(*53C55,C9,C(8((**33-5C,C5,A(39*,5555+5,;/57(;,14,,,65*,,.5???8::::::C:9999****::=====7=::::998555555@55555****8888888488888585',
  },
  Courier: {
    palette: [0, 400, 549, 576, 600],
    indices:
      ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,(,(,,,,,,,,,,,(,((,,,,,,,,,,,,(,,,,,,,,,,,,,,,(,,)*,,,+,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,*,,,,,,,,',
  },
};

/** Advance width of one WinAnsi code point, in 1/1000 em. */
export function glyphWidth(font: string, code: number): number {
  const table = FONT_WIDTHS[font];
  if (!table || code < FIRST_CODE || code > LAST_CODE) return 0;
  const index = table.indices.charCodeAt(code - FIRST_CODE) - INDEX_OFFSET;
  return table.palette[index] ?? 0;
}
